### ISSUE TITLE
Configuration Page of Scenario

### ISSUE THREAD

**Issue by Lolo4ever** [Ledz-go/Front#4]
Displays interogation mark icon for each item in the "PENDING" list. User will click on the icons to open a dialog page to set up the DMX light and get a small tutorial on how to set up the light.  In the dialog page the user will also enter the model name of the DMX light. Sends the info back to the back. end
# Validation Test
- [ ] Display PENDING plugs as icons
- [ ] Opens dialog on click
- [ ] Changes are saved

# Implementation Plan
- HTTP GET /pending from front to back to get the PENDING list
- HTTP POST /room (aka the name of the room being configured) to send the list of DMX light
<img width="465" alt="Screenshot 2021-10-07 at 11 11 12" src="https://user-images.githubusercontent.com/56384031/136355348-30e9c1ab-62b8-41ae-9824-0f08961751da.png">
